/**
 * Generate `src/grammars/catalog.ts` from the eager `languages` array.
 *
 * The catalog carries language metadata with no grammar attached, plus a
 * dynamic import per language. That is what lets a consumer resolve
 * "which language is this file" and load one grammar, instead of pulling all
 * forty eight into the bundle to answer a question about extensions.
 *
 * Generated rather than hand-written so the two cannot drift in what they list.
 * `test/catalog.test.ts` holds them to agreeing, in both directions, so adding
 * a language and forgetting to run this is a failing test rather than a
 * silently missing language.
 *
 * Run with: bun run scripts/generate-catalog.ts
 */

import { readdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { languages } from '../src/grammars'

const here = dirname(fileURLToPath(import.meta.url))
const grammarsDir = join(here, '..', 'src', 'grammars')
const outputPath = join(grammarsDir, 'catalog.ts')

/**
 * Which file a grammar lives in.
 *
 * Matched by the grammar's own `name`, then by the language id, then by alias,
 * because the three agree for most languages and the exceptions are not
 * consistent about which one the filename follows.
 */
function moduleForLanguage(id: string, aliases: string[], grammarName: string): string {
  const files = new Set(
    readdirSync(grammarsDir)
      .filter(file => file.endsWith('.ts') && file !== 'index.ts' && file !== 'catalog.ts')
      .map(file => file.slice(0, -3)),
  )

  for (const candidate of [grammarName, id, ...aliases]) {
    if (candidate && files.has(candidate))
      return candidate
  }

  throw new Error(`No grammar module found for language "${id}" (grammar name "${grammarName}")`)
}

/** The exported binding inside a grammar module, e.g. `javascriptGrammar`. */
async function exportForModule(moduleName: string): Promise<string> {
  const text = await Bun.file(join(grammarsDir, `${moduleName}.ts`)).text()
  const match = /export const (\w+Grammar)\b/.exec(text)
  if (!match)
    throw new Error(`No exported grammar found in ${moduleName}.ts`)

  return match[1]!
}

const entries = await Promise.all(languages.map(async (language) => {
  const moduleName = moduleForLanguage(language.id, language.aliases ?? [], language.grammar.name)
  const exportName = await exportForModule(moduleName)

  return {
    id: language.id,
    name: language.name,
    aliases: language.aliases ?? [],
    extensions: language.extensions ?? [],
    scopeName: language.grammar.scopeName,
    moduleName,
    exportName,
  }
}))

/** Single quotes and spaced arrays, so the output passes the repo's own lint. */
function literal(value: string | string[]): string {
  if (Array.isArray(value))
    return `[${value.map(item => literal(item)).join(', ')}]`

  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, '\\\'')}'`
}

const body = entries.map(entry => `  {
    id: ${literal(entry.id)},
    name: ${literal(entry.name)},
    aliases: ${literal(entry.aliases)},
    extensions: ${literal(entry.extensions)},
    scopeName: ${literal(entry.scopeName)},
    load: async () => (await import('./${entry.moduleName}')).${entry.exportName},
  },`).join('\n')

const output = `// Generated by scripts/generate-catalog.ts. Do not edit by hand.
//
// Language metadata with no grammar attached, and one dynamic import each. A
// consumer that only needs to know which language a file is, or that needs one
// grammar, pays for one grammar rather than for all ${entries.length}.
//
// \`test/catalog.test.ts\` asserts this agrees with the eager \`languages\`
// array in both directions, so regenerating is enforced rather than remembered.

import type { LanguageDescriptor } from '../types'

export const catalog: LanguageDescriptor[] = [
${body}
]
`

await Bun.write(outputPath, output)
console.log(`Wrote ${outputPath} with ${entries.length} languages`)
